#!/usr/bin/env bash

# Strict Bash Mode
set -euo pipefail
here="${BASH_SOURCE[0]%/*}"
source "$here/../shared/functions.sh"

loud green echo "# ~${PWD/$HOME/}/box.env"
loud cyan cat "${PWD}/box.env"

# import box, venue etc.
read_env "${PWD}/box.env"

loud green echo "# ~${PWD/$HOME/}/${venue}.env"
loud cyan cat "${PWD}/${venue}.env"

# import shape,image etc.
read_env "${PWD}/${venue}.env"

# import box again to allow for overriding venue
read_env "${PWD}/box.env"

