#!/usr/bin/env bash

# Strict Bash Mode
set -euo pipefail

here="${BASH_SOURCE[0]%/*}"
source "$here/../shared/functions.sh"

source "$here/use"

oci compute image list --compartment-id $TENANCY --all --query "data[*].\"display-name\"" 
