#!/usr/bin/env bash

QUIET=true source "${BASH_SOURCE[0]%/*}/box"
 
echo oci compute image list --compartment-id $TENANCY \
     --query "data[?starts_with(@.\"display-name\", '$image') ]"

# Get image ID (first match)
oci compute image list --compartment-id $TENANCY --all \
     --query "data[?starts_with( @.\"display-name\", '$image') ] | [0].id"
