#!/usr/bin/env bash

# Strict Bash Mode
set -euo pipefail
here="${BASH_SOURCE[0]%/*}"
source "$here/../shared/functions.sh"

[[ -z ${TENANCY+x} ]] && source ${BASH_SOURCE[0]%/*}/use ""

oci compute shape list --compartment-id $TENANCY --all # --query "data[*].\"shape\"" 