#!/usr/bin/env bash

QUIET=true source "${BASH_SOURCE[0]%/*}/box"
 
green oci compute instance list --compartment-id $TENANCY --output table \
    --query "data[*].{\"Name\":\"display-name\",\"State\":\"lifecycle-state\"}" 
