#!/usr/bin/env bash

QUIET=true source "${BASH_SOURCE[0]%/*}/box"
 
oci network subnet list --compartment-id $TENANCY # --query 'data[*].{VCNID:id,VCNName:"display-name"}'

if [[ -n ${subnet+x} ]]; then

    printf "Current: $subnet "

    oci network subnet list --compartment-id $TENANCY --all --raw-output \
        --query "data[? \"display-name\" == '$subnet' ].id | [0]"

fi