#!/usr/bin/env bash

QUIET=true source "${BASH_SOURCE[0]%/*}/box"

name_ip=$($here/action ip $@)
name="${name_ip% *}"
ip="${name_ip#* }"

[[ -z "$ip" ]] && echo "IP not found" && exit

echo "New IP: $ip"
sed_script="s/Hostname [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+/Hostname ${ip}/ ;"

shhd yellow show name_ip name ip sed_script

for config in *.ssh_config
do
    echo "Updating: $config"
    grep -q "$box" "$config" \
        && sed -i "$sed_script" "$config" \
        && cat "$config"
done