#!/usr/bin/env bash

# Strict Bash Mode
set -euo pipefail
here="${BASH_SOURCE[0]%/*}"
source "$here/../shared/functions.sh"

[[ -z ${TENANCY+x} ]] && source ${BASH_SOURCE[0]%/*}/use "" 

oci network vcn list --compartment-id $TENANCY # --query 'data[*].{VCNID:id,VCNName:"display-name"}'
