#!/usr/bin/env bash

# install as an alias
# $> alias bf=~/angelbox/bashaform/bashaform

# install as a command
# $> ln -sT ~/angelbox/bashaform/bashaform ~/.local/bin/bf

# usage
# $> bf oci/status

bashaform=$(dirname $(readlink -f "$BASH_SOURCE"))

[[ ! -f box.env ]] && echo "No box.env file found, change to a directory with a server configuration" && exit 1

$bashaform/$@
