#!/usr/bin/env bash

# Strict Bash Mode
set -euo pipefail

bashaform="${BASH_SOURCE[0]%/*}"
source "${bashaform}/shared/functions.sh"

read_box box.env # first pass

[[ -z "${cloud:-}" ]] && error "cloud is not set in box.env" && exit 1

source "${bashaform}/${cloud}/_functions.sh"

read_named "${cloud}_location"
read_named "${cloud}_instance"
QUIET=true read_box box.env # second pass - allow box.env to override defaults

if declare -f read_cloud_config_file > /dev/null
then
    read_cloud_config_file
fi

