#!/usr/bin/env bash

set -euo pipefail

bashaform="${BASH_SOURCE[0]%/*}"
cmd="${BASH_SOURCE[0]##*/}"
source "${bashaform}/shared/functions.sh"

QUIET=true read_box box.env # first pass

[[ -z "${cloud:-}" ]] && loud red echo "cloud is not set in box.env" && exit 1

name_ip=$($bashaform/$cloud/action ip $@)
name="${name_ip% *}"
ip="${name_ip#* }"

[[ -z "$ip" ]] && echo "IP not found" && exit

echo "New IP: $ip"
sed_script="s/Hostname [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+/Hostname ${ip}/ ;"

debug yellow show name_ip name ip sed_script

for config in *.ssh_config
do
    echo "Updating: $config"
    grep -q "$box" "$config" \
        && sed -i "$sed_script" "$config" \
        && cat "$config"
done