#!/usr/bin/env bash

# Strict Bash Mode
set -euo pipefail

here="${BASH_SOURCE[0]%/*}"
source "$here/../shared/functions.sh"

read_box box.env # first pass
source "$here/../${cloud}/functions.sh"

read_named "${cloud}_location"
read_named "${cloud}_instance"
read_box box.env # second pass - allow box.env to override defaults

aws_config_file="${aws_config_file:-}"
aws_config_file="${aws_config_file/\~/$HOME}"
aws_config_file="${aws_config_file/\$HOME/$HOME}"

source "$here/use" "${aws_config:-DEFAULT}" "${aws_config_file}"

loud green printf "\n[%s:%s]\n...\n" "${aws_config_file:-~/.aws/config}" "${aws_config:-DEFAULT}"
loud cyan echo "TENANCY=${TENANCY}$NL..."
